/* eslint-disable */
/**
 * 该文件是为了按需加载，剔除掉了一些不需要的框架组件。
 * 减少了编译支持库包大小
 *
 * 当需要更多组件依赖时，在该文件加入即可
 */
 import Vue from 'vue'
 import {
   Button,
   Cell,
   CellGroup,
   Icon,
   Image,
   Col,
   Row,
   Popup,
   Toast,
   Checkbox,
   CheckboxGroup,
   DatetimePicker,
   Field,
   Form,
   NumberKeyboard,
   Picker,
   RadioGroup,
   Radio,
   Search,
   Stepper,
   Switch,
   Uploader,
   ActionSheet,
   Dialog,
   Loading,
   Notify,
   Divider,
   Empty,
   ImagePreview,
   NoticeBar,
   Swipe,
   SwipeItem,
   Tag,
   Grid,
   GridItem,
   Tab,
   Tabs,
   Tabbar,
   TabbarItem,
   Area,
   Collapse,
   CollapseItem,
   ShareSheet,
   List,
   Overlay 
 } from 'vant'
 
 Vue.use(Overlay)
 Vue.use(Button)
 Vue.use(Cell)
 Vue.use(CellGroup)
 Vue.use(Icon)
 Vue.use(Image)
 Vue.use(Col)
 Vue.use(Row)
 Vue.use(Popup)
 Vue.use(Toast)
 Vue.use(Checkbox)
 Vue.use(CheckboxGroup)
 Vue.use(DatetimePicker)
 Vue.use(Field)
 Vue.use(Form)
 Vue.use(NumberKeyboard)
 Vue.use(Picker)
 Vue.use(RadioGroup)
 Vue.use(Radio)
 Vue.use(Search)
 Vue.use(Stepper)
 Vue.use(Switch)
 Vue.use(Uploader)
 Vue.use(ActionSheet)
 Vue.use(Dialog)
 Vue.use(Loading)
 Vue.use(Notify)
 Vue.use(Divider)
 Vue.use(Empty)
 Vue.use(ImagePreview)
 Vue.use(NoticeBar)
 Vue.use(Swipe)
 Vue.use(SwipeItem)
 Vue.use(Tag)
 Vue.use(Grid)
 Vue.use(GridItem)
 Vue.use(Tab)
 Vue.use(Tabs)
 Vue.use(Tabbar)
 Vue.use(TabbarItem)
 Vue.use(Area)
 Vue.use(Collapse)
 Vue.use(CollapseItem)
 Vue.use(ShareSheet)
 Vue.use(List)
 